### REGISTR A USER
POST localhost:8080/api/v1/auth/registration
Content-Type: application/json
Accept-Language: EN

{
  "name": "Muzaffar",
  "username": "ortiqovmuzaffar171@gmail.com",
  "password": "12345"
}

### Registration Email  Verification
GET localhost:8080/api/v1/auth/registration/email-verification/eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIwMDZkODhlMy1lMGZmLTRhZjAtYmUxZC1iZWY4YTJmYTczMmEiLCJpYXQiOjE3NDk4NzY5NTksImV4cCI6MTc0OTg4MDU1OX0.GMsCqNTLvRsSX4Tfc163XjXR2rrpel0aTOUayre6aJUUqiDjxYDvVxZ2FzQJkHERcoUj4VZzSEIjjDb7shG-ZA?lang=EN
Accept-Language: EN

### Registration Sms Verification
POST localhost:8080/api/v1/auth/registration/sms-verification
Content-Type: application/json
Accept-Language: EN

{
  "phone": "998942702363",
  "code": "47542"

}

### Registration Sms Verification Resend
POST localhost:8080/api/v1/auth/registration/sms-verification-resend
Content-Type: application/json
Accept-Language: EN

{
  "phone": "+998942702363"

}


### LOGIN
POST localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "muzaffarmike2@gmail.com",
  "password": "12345"
}

### Password Reset
POST localhost:8080/api/v1/auth/password-reset
Content-Type: application/json
Accept-Language: EN

{
  "username": "ortiqovmuzaffar171@gmail.com"
}

### Reset Password Verification
POST localhost:8080/api/v1/auth/password-reset-confirm
Content-Type: application/json
Accept-Language: EN

{
  "username": "ortiqovmuzaffar171@gmail.com",
  "confirmCode": "37681",
  "password": "12345"
}




