### Update profile name and surname
PUT localhost:8080/api/v1/profile/detail
Content-Type: application/json
Accept-Language: UZ
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwiaWQiOiIwYzQzNjgxZi0xZGEzLTQ0MmEtYTk4Ni0yNjAyMjBiZTc0MjkiLCJzdWIiOiJvcnRpcW92bXV6YWZmYXIxNzFAZ21haWwuY29tIiwiaWF0IjoxNzQ5NTQ5MjA1LCJleHAiOjE3NDk2MzU2MDV9.5pilhCfRq-6VO7Rdc7lUz2mgnzQuCYyA1iVKdU0hDH_7a3CsYPzyrYmMbSVSoc0KIRt5K5G8Yb7eLT01EoAkYA

{
  "name": "Raffazum",
  "surname": "Ortiqov"
}

### Update profile password
PUT localhost:8080/api/v1/profile/password
Content-Type: application/json
Accept-Language: UZ
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwiaWQiOiIwYzQzNjgxZi0xZGEzLTQ0MmEtYTk4Ni0yNjAyMjBiZTc0MjkiLCJzdWIiOiJvcnRpcW92bXV6YWZmYXIxNzFAZ21haWwuY29tIiwiaWF0IjoxNzQ5NTUwMjA2LCJleHAiOjE3NDk2MzY2MDZ9.gIzcEjFZy_hs8XXkRq6pKaCfwW4mbCKlsNo6cQdEafsDySyq2iLNCGdiC75AVDqLoGhK_auenNKQHkO_DSU_EQ

{
  "currentPassword": "12345",
  "newPassword": "777"
}

### Update profile username
PUT localhost:8080/api/v1/profile/username
Content-Type: application/json
Accept-Language: UZ
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwiaWQiOiIwYzQzNjgxZi0xZGEzLTQ0MmEtYTk4Ni0yNjAyMjBiZTc0MjkiLCJzdWIiOiJtdXphZmZhcm1pa2UyQGdtYWlsLmNvbSIsImlhdCI6MTc0OTYxODQ5NSwiZXhwIjoxNzQ5NzA0ODk1fQ.fKw_W6vZd33mK37PnsNBR_ckI3h8rfdA5lzrdyv5dDVGssxMbRtmKMOreY4H6HpcmvIkki5Pt735_wZs0zB19A

{
  "username": "+998942702363"
}

### Update profile username confirm
PUT localhost:8080/api/v1/profile/username-confirmation
Content-Type: application/json
Accept-Language: EN
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwiaWQiOiIwYzQzNjgxZi0xZGEzLTQ0MmEtYTk4Ni0yNjAyMjBiZTc0MjkiLCJzdWIiOiJvcnRpcW92bXV6YWZmYXIxNzFAZ21haWwuY29tIiwiaWF0IjoxNzQ5NjE3MzY3LCJleHAiOjE3NDk3MDM3Njd9.1C1a1IZOJJd9ZFqzz6DBgBsmwFXXbZkYKyUAtIWMwToPWrWlQ2EnrnL7skP3b0MulY39SHHzFQy42geOWUlMzg

{
  "code": "91366"
}

### CREATE A NEW PROFILE
POST localhost:8080/api/v1/profile/create
Content-Type: application/json
Accept-Language: EN
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTixST0xFX1VTRVIiLCJpZCI6ImJhNzY1YjJiLTUzZWItNDEwZi1hOTJjLWNhNDUxNjgxYmFlMSIsInN1YiI6Im11emFmZmFybWlrZTJAZ21haWwuY29tIiwiaWF0IjoxNzQ5NjM0OTU3LCJleHAiOjE3NDk3MjEzNTd9.bxV1mJMQ9l-71o4fnocYBR5scUYuw9k9c1o4NwgUkKUo15JHuL5goWlIzty2Z04o3PZJfuyYI6NGP2ZZd6aUqg

{
  "name": "Samandar",
  "surname": "Nematullayev",
  "username": "muzaffarortiqov19@gmail.com",
  "status": "ACTIVE",
  "password": "12345",
  "roleList": [
    "ROLE_USER","ROLE_MODERATOR"
  ]
}

### UPDATE PROFILE DETAIL BY ADMIN
PUT localhost:8080/api/v1/profile/admin/detail/0c43681f-1da3-442a-a986-260220be7429
Content-Type: application/json
Accept-Language: UZ
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTixST0xFX1VTRVIiLCJpZCI6ImJhNzY1YjJiLTUzZWItNDEwZi1hOTJjLWNhNDUxNjgxYmFlMSIsInN1YiI6Im11emFmZmFybWlrZTJAZ21haWwuY29tIiwiaWF0IjoxNzQ5NzQxMTQ1LCJleHAiOjE3NDk4Mjc1NDV9.zLnZDiIqiUybOYcWYC5xdY9CXCwnQ9GPaEPXlF8TgsSlK4f1CjNhneonycZew2IQsaHIMgh6PutfZUsUFj9Obw

{
  "name": "Raffazum",
  "surname": "Ortiqov",
  "status": "IN_REGISTRATION",
  "roles": ["ROLE_MODERATOR", "ROLE_USER","ROLE_PUBLISHER"]
}

### PAGINATION
PUT localhost:8080/api/v1/profile/admin/pagination?page=1&size=3
Content-Type: application/json
Accept-Language: UZ
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTixST0xFX1VTRVIiLCJpZCI6ImJhNzY1YjJiLTUzZWItNDEwZi1hOTJjLWNhNDUxNjgxYmFlMSIsInN1YiI6Im11emFmZmFybWlrZTJAZ21haWwuY29tIiwiaWF0IjoxNzQ5NzQxMTQ1LCJleHAiOjE3NDk4Mjc1NDV9.zLnZDiIqiUybOYcWYC5xdY9CXCwnQ9GPaEPXlF8TgsSlK4f1CjNhneonycZew2IQsaHIMgh6PutfZUsUFj9Obw

### DELETE PROFILE
DELETE localhost:8080/api/v1/profile/admin/delete/0c43681f-1da3-442a-a986-260220be7429
Content-Type: application/json
Accept-Language: UZ
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTixST0xFX1VTRVIiLCJpZCI6ImJhNzY1YjJiLTUzZWItNDEwZi1hOTJjLWNhNDUxNjgxYmFlMSIsInN1YiI6Im11emFmZmFybWlrZTJAZ21haWwuY29tIiwiaWF0IjoxNzQ5NzQxMTQ1LCJleHAiOjE3NDk4Mjc1NDV9.zLnZDiIqiUybOYcWYC5xdY9CXCwnQ9GPaEPXlF8TgsSlK4f1CjNhneonycZew2IQsaHIMgh6PutfZUsUFj9Obw

### FILTER
POST localhost:8080/api/v1/profile/admin/filter
Content-Type: application/json
Accept-Language: UZ
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTixST0xFX1VTRVIiLCJpZCI6ImJhNzY1YjJiLTUzZWItNDEwZi1hOTJjLWNhNDUxNjgxYmFlMSIsInN1YiI6Im11emFmZmFybWlrZTJAZ21haWwuY29tIiwiaWF0IjoxNzQ5NzQxMTQ1LCJleHAiOjE3NDk4Mjc1NDV9.zLnZDiIqiUybOYcWYC5xdY9CXCwnQ9GPaEPXlF8TgsSlK4f1CjNhneonycZew2IQsaHIMgh6PutfZUsUFj9Obw

{
  "createdDateTo": "2025-06-11T14:35:22.123"
}


#### Update profile photo
PUT localhost:8080/api/v1/profile/photo
Content-Type: application/json
Accept-Language: UZ
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSLFJPTEVfTU9ERVJBVE9SIiwiaWQiOiI1M2U0MTY1YS0xODhkLTRjNDctOGIzZS03MmIxNTQ4NDNmMjEiLCJzdWIiOiJtdXphZmZhcm9ydGlxb3YxOUBnbWFpbC5jb20iLCJpYXQiOjE3NDk4MjEzOTgsImV4cCI6MTc0OTkwNzc5OH0.66FtbVKZ4FSR0tb0Ha5XB8Q4eICkVZKvxBBrXNvhM61EmHNsxLpcgOghyo_uYBLgM11Jn--ubiZQl6U-iU4kFw

{
  "photoId": "6e9a7490-965b-4242-90c5-894fbe20fa1b.jpg"
}


